version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 127.0.0.1"
    container_name: conversion-app
    volumes:
      - .:/app
    ports:
      - "8000:8000"